### PR TITLE
Release 0.5.1

### PR DESCRIPTION
**Pull request by dwhswenson**
Minor update, mainly to add compatibility with recent releases of other software. Pandas 1.0 brought major changes to the its treatment of sparse matrices, which broke the way we convert contact matrices to Pandas DataFrames. MDTraj no longer supports Python 2, so we no longer test against Python 2. Python 2 support will be officially dropped in the next release of Contact Map Explorer.

# Miscellaneous improvements

* Drop Py27 and Win32; add Py38 (#75) #upstream_changed
* Fix RTD docs build (#72) #docs
* Fixes for sparse matrix in Pandas 1.0 (#69) #upstream_changed

### CODE REVIEW

**Comment by dwhswenson** [comment]
close/reopen to get travis to run with an update to autorelease

**Comment by sroet** [comment]
feel free to merge once you are satisfied with it ;)

**Comment by dwhswenson** [comment]
@sroet : Thanks -- working on some issues with autorelease now (Travis changed things). See https://travis-ci.community/t/9290. I'll hold off on merge until I can have our autorelease import point to a version, instead of an experimental branch.

**Comment by dwhswenson** [comment]
It turns out that the problem with autorelease was that I was inconsistent on spaces vs underscores. Anyway, new release of autorelease is out, and now we can finally release Contact Map Explorer 0.5.1.

**Pull request merged**
