### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by dwhswenson**
The most obvious change in Contact Map Explorer 0.5.0 is the new name: the project is officially called Contact Map Explorer!

It also includes several small updates, and an important bugfix when dealing with nonperiodic trajectories (without unitcell vectors).

Also, @sroet is now a core contributor, so we don't list his name next to every PR he contributes in the changelog.

## Bug fixes

* Fix when no unitcells are reported (nonperiodic systems) (#64 @nffaruk, #65)

## Miscellaneous improvements
* Better colorbar scaling (#64 @nffaruk)
* Rename to Contact Map Explorer (#61)
* Miscellaneous improvements to CI (#41, #63, #66)
* Pin `pandas<1.0` (#70) #upstream_changed

### CODE REVIEW

**Comment by dwhswenson** [comment]
Problems with sparse matrix changes in pandas 1.0 (released 2 days ago). I'll add another PR to fix that, and merge it into this one once the fix is in master.

**Comment by sroet** [comment]
Do we want to drop 2.7 support as well for this version, or just for the next one (my vote is the next one)?

**Comment by dwhswenson** [comment]
I'd say next one (0.6.0 -- I think/hope we'll have a 0.5.1 fix for the pandas pin soon).

For some reason, Travis isn't triggering the autorelease scripts now. Trying to fix that.

**Comment by dwhswenson** [comment]
Giving this until morning for further comment. If no objections in the next 12 hours, I merge and it automatically releases, with the top post here as the release notes.

**Comment by sroet** [comment]
LGTM, feel free to merge

**Pull request merged**
