### PR TITLE
Switch to GitHub Actions and CodeCov

### LINKED ISSUE #103: What to do with the new travis.com plan?
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

So the big point for us would be:
> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

So that seems they are giving a *one time* allotment of 1000 minutes (which would get us 67 nightly builds, at 15 min per build, and without you as a user running any other jobs) (The free plan explicitly says it does not replenish credits)

I found two options to go forward:
1) Apply for repeated open-source credits for this project
> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:

   > Your account name and VCS provider (like travis-ci.com/github/[your account name] )
    How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat
    the process to  request more or discuss a renewable amount)

2) Switch to Azure for CI https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/

@dwhswenson do you have any other options/ an opinion on which way to go forward? (No worries if you don't have time to figure out the switch, I might be able to spend a couple hours figuring that out)

Looking around it seems like Azure is getting more and more adaptation so I am +0.5 on that option but I am willing to default to your opinion here

### PR DESCRIPTION
**Pull request by dwhswenson**
Resolves #103.

I think I've got Autorelease working on GitHub Actions now. There may be a few more bumps along the way, but with releases done for Autorelease, CodeModel, and OpenPathSampling CLI, I think this workflow is ready for Contact Map Explorer (and then OPS).

Autorelease has partial support for Azure pipelines, but unfortunately you can't identify the target branch at pipeline planning time, so you *always* show the (usually skipped) testpypi deployment stage. With Actions, it only shows when it runs.

Autorelease action scripts are vendored with `autorelease vendor actions`, and can be updated with the same.

### CODE REVIEW

**Comment by dwhswenson** [comment]
This is ready for review. In reviewing, note that the files `.github/workflows/autorelease-*` are vendored from Autorelease. (I should probably make sure that the vendored files have a comment at the top to that effect... something for the next release of Autorelease!)

Also in here: added Python 3.9 to the test matrix and dropped uploading of coverage to Codacy, because it seemed to be having a lot of trouble (are we actually using Codacy for anything? We can probably also drop that badge; I only pay attention to CodeClimate's feedback. I added the extra badge there because otherwise CodeClimate was on its own line; now it gets to share with Binder, too!).

Additionally, I moved the Binder badge to the left of that line. The two things you're most likely to click on, docs and Binder, are at the leftmost edge.

I'd be interested in switching from Coveralls to CodeCov for coverage info, and can do that in this PR if it makes sense to. I switched to CodeCov on OpenPathSampling CLI and on CodeModel, will probably switch OPS over when I switch from Travis, too. I've never liked the aesthetic of Coveralls, and now CodeCov handles parallel builds reasonably well. (Only issue is that it thinks scheduled/cron builds are more parallel results coming in, so maybe don't upload coverage for those.)

**Comment by sroet** [comment]
LGTM, I like all the nice checkmarks for GA. Feel free to merge.

> I'd be interested in switching from Coveralls to CodeCov for coverage info, and can do that in this PR if it makes sense to. I switched to CodeCov on OpenPathSampling CLI and on CodeModel, will probably switch OPS over when I switch from Travis, too. I've never liked the aesthetic of Coveralls, and now CodeCov handles parallel builds reasonably well. (Only issue is that it thinks scheduled/cron builds are more parallel results coming in, so maybe don't upload coverage for those.)

Splitting it out to a seperate PR might make for cleaner release notes? If so, that option has my preference +0.5 ?

**Review by sroet — APPROVED** [review]

**Comment by dwhswenson** [comment]
> Splitting it out to a seperate PR might make for cleaner release notes? If so, that option has my preference +0.5 ?

I just noticed that coveralls isn't reporting back in the checks (apparently I need to do something to tell it to stop [awaiting completion](https://coveralls.io/jobs/72498125)?), so I think it may be better to switch to codecov here.

**Comment by dwhswenson** [comment]
> I don't see code-cov reporting back either? Or am I looking at the wrong place (I expected it to be somewhere in the checks tab)

I think it waits until everything is done, so it is still waiting on AppVeyor. At the link under the action for it, I see:

image

**Comment by dwhswenson** [comment]
Nope... apparently not. I was trying to use the Action for it; I'll use the script instead (which is what I did elsewhere)

**Comment by dwhswenson** [comment]
It didn't show up in checks because I needed to give it permission on GitHub (which I did after the commits completed). Obviously it now knows how to talk to us, though!

**Comment by sroet** [comment]
> It didn't show up in checks because I needed to give it permission on GitHub (which I did after the commits completed). Obviously it now knows how to talk to us, though!

Looks like it! Feel free to merge!

**Pull request merged**
