### PR TITLE
Rename to Contact Map Explorer

### PR DESCRIPTION
**Pull request by dwhswenson**
This PR does 3 things:

1. Rename everything to "Contact Map Explorer". Here are my reasons for that:
    * Emphasizes that this isn't just a code for one-off calculations of a single contact map (or contact frequency, as we call them). This is about taking the resulting data and exploring it more deeply, as I think our example notebooks show very clearly. (Also part of our selling point for any potential article to make of this.)
    * Previous unclear terminology: when to refer to the package as `contact_map` and when to call it "Contact Map" or "Contact Maps", and in general how to refer to it ("the `contact_map` package` feels clumsy compared to a proper noun.)
    * Related: how do I talk about it elsewhere? Currently, when talking about coding practices, it's "we do something similar with my contact maps code (link)." I'd rather replace "my contact maps code" with a proper noun, like "Contact Map Explorer".
    * Generally distinguish from other stuff out there, and become more searchable (if the name starts to mean anything to anyone).

    I'm open to argument or suggestion for better names.

2. Promotes @sroet to co-author, as is appropriate to his contributions. I'm much less open to debate on this. Sorry Sander, you're stuck with it ;-) For things that are single-maintainer, I keep that role, but I intend to add Sander as co-maintainer where possible (e.g., conda-forge), starting with the next release.

3. Bumps copyright year. That's definitely not objectionable.

I think I fixed everything relevant to these points, but it is possible that project name/authorship/copyright is hiding somewhere I haven't seen. We'll update if I missed things.

### CODE REVIEW

**Comment by dwhswenson** [comment]
I had intentionally left `setup.py` stuff single-author because I was under the impression that PyPI had problems with multiple-author setups. Looking into it again, the particular problem was that it choked on multiple author emails. However, this has been fixed. Best summary of the story that I've found is https://github.com/takluyver/flit/issues/153 and various issues linked therein (and linked within that next level, too)

I'll that, following the example at https://packaging.python.org/specifications/core-metadata/#author-email. Which email address should I use for you?

**Comment by dwhswenson** [comment]
> we still have a `contact_map` reference in `docs/installing.rst` which we might or might not change (no strong preference from me)

Yeah, I think in that case it is referring to the package name. Technically, I think our recommended style is:

* Project name (referring to this in normal text): Contact Map Explorer
* Downloadable package name (referring to the package that is downloaded from `conda-forge` or PyPI): `contact_map` -- note that this should be in monospace font.

Granted, I'm sure that I'll mix up those two terms all the time (calling it the "Contact Map Explorer package"), but when it doubt, that's the guideline to use.

**Comment by sroet** [comment]
Please use my hotmail (as that one is linked to github)

**Comment by dwhswenson** [comment]
@sroet : `setup.py` has been updated (and even with your actual email address, the second time around, when I realized that `${GITHUB_USERNAME}@whatever.xyz` isn't accurate for either of us.)

**Comment by sroet** [comment]
> @sroet : `setup.py` has been updated (and even with your actual email address, the second time around, when I realized that `${GITHUB_USERNAME}@whatever.xyz` isn't accurate for either of us.)

Perfect, last requested change left is about the block comment at the start of `contact_map/contact_map.py`

**Comment by dwhswenson** [comment]
> Perfect, last requested change left is about the block comment at the start of `contact_map/contact_map.py`

Sorry, overlooked that. I removed those lines. They date back to when [this was a gist](https://gist.github.com/dwhswenson/41104499495adaf443882e229cba75ef). Now author and license info should come from `setup.py` and the `LICENSE` file.

**Pull request merged**
